function [] = plot_metrics_t2(alpha, TP_h, TP_f, TP_t, TN_h, TN_f, TN_t, FP_h, FP_f, FP_t, FN_h, FN_f, FN_t)

    fprintf('\nPlotting TP, TN, FP, FN...')
    figure(1)
    subplot(2,2,1)
    plot(alpha,TP_h,alpha,TP_f,alpha,TP_t)
    xlabel('Alpha')
    ylabel('TP')
    legend('TP Highway','TP Fall','TP Traffic')
    title('TRUE POSITIVE')

    subplot(2,2,2)
    plot(alpha,TN_h,alpha,TN_f,alpha,TN_t)
    xlabel('Alpha')
    ylabel('TN')
    legend('TN Highway','TN Fall','TN Traffic')
    title('TRUE NEGATIVE')

    subplot(2,2,3)
    plot(alpha,FP_h,alpha,FP_f,alpha,FP_t)
    xlabel('Alpha')
    ylabel('FP')
    legend('FP Highway','FP Fall','FP Traffic')
    title('FALSE POSITIVE')

    subplot(2,2,4)
    plot(alpha,FN_h,alpha,FN_f,alpha,FN_t)
    xlabel('Alpha')
    ylabel('FN')
    legend('FN Highway','FN Fall','FN Traffic')
    title('FALSE NEGATIVE')